# Generated by Django 5.2.3 on 2025-06-27 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('merge', 'Merge PDFs'), ('split', 'Split PDF'), ('compress', 'Compress PDF'), ('convert_to_image', 'Convert PDF to Image'), ('convert_from_image', 'Convert Image to PDF'), ('rotate', 'Rotate PDF'), ('protect', 'Protect PDF'), ('unlock', 'Unlock PDF')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_files', models.JSONField(default=list, help_text='List of input file UUIDs')),
                ('output_file', models.CharField(blank=True, help_text='Output file UUID', max_length=100, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Operation-specific parameters')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'pdf_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
